### ISSUE TITLE
Does not download comics (AttributeError: 'NoneType' object has no attribute 'absolute_links')

### ISSUE THREAD

**Issue by wyatt8740** [JeremyRuhland/webtoon-dl.py#3]
Fails to download comics with the error `AttributeError: 'NoneType' object has no attribute 'absolute_links'`.

    $ python3 ./webtoon-dl.py -o /path/to/erma https://www.webtoons.com/en/challenge/erma/list?title_no=170650
    Finding comics...
    Getting gallery from erma...
    Traceback (most recent call last):
      File "./webtoon-dl.py", line 152, in <module>
        comic_list = process_url_list(args.webtoon_url)
      File "./webtoon-dl.py", line 75, in process_url_list
        processed_list.extend(process_url_list(comics_from_gallery(url)))
      File "./webtoon-dl.py", line 47, in comics_from_gallery
        comics_list.extend(page.html.find('#_listUl', first=True).absolute_links)
    AttributeError: 'NoneType' object has no attribute 'absolute_links'

I am using Debian Sid, Python 3.8.3rc1.

Is this just a PEBKAC? (Is my URL the kind that's expected?)

**Comment by goopypanther** [comment]
Weird, I'm not sure. I just ran `python3 ./webtoon-dl.py -o /path/to/erma https://www.webtoons.com/en/challenge/erma/list?title_no=170650` on my system and it worked as expected.
I was able to replicate your error by changing `#_listUl` to `_listUl` on ln 47 but that doesn't really explain anything.
To make matters stranger, when I visit the page in my browser and inspect the HTML the tag I'm searching on does not have a pound sign in it. Maybe its loading differently for different clients? User agent or something?

**Comment by Thunderhawk2001** [comment]
Getting the same error message.

I'm on Windows 10 with Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
